# HubSpot Integration API Tests
#
# This file allows you to test your API endpoints directly from VS Code.
# You will need the "REST Client" extension by Huachao Mao.
#
# To use:
# 1. Fill in the variables below.
# 2. Click the "Send Request" link that appears above each request.

# --- Variables ---
# These variables will be used in the requests below.
@baseUrl = http://localhost:8000/v1
@hubspotPrefix = /hubspot
@org_id = test_org_123
@user_id = test_user_456

###
# 1. Authorize Endpoint
#
# Triggers the HubSpot OAuth 2.0 flow.
# The server should respond with a 307 Temporary Redirect to a HubSpot URL.
# Note: The REST Client will not automatically follow this redirect. You can
# see the redirect URL in the response headers.
POST {{baseUrl}}{{hubspotPrefix}}/oauth2/authorize
Content-Type: application/x-www-form-urlencoded

org_id={{org_id}}&user_id={{user_id}}


###
# 2. Get Credentials (No Auth)
#
# Attempts to get credentials for a user who has not yet authenticated.
# This should fail with a 404 Not Found error.
GET {{baseUrl}}{{hubspotPrefix}}/credentials?user_id={{user_id}}&org_id={{org_id}}


###
# 3. Get Items (No Auth)
#
# Attempts to get HubSpot items for a user who has not yet authenticated.
# This should fail with a 401 Unauthorized or 404 Not Found error.
GET {{baseUrl}}{{hubspotPrefix}}/items?user_id={{user_id}}&org_id={{org_id}}


###
# 4. OAuth Callback (Invalid)
#
# Simulates HubSpot redirecting back to your application with an invalid code.
# This tests the error handling of your callback endpoint.
# It should respond with a 4xx or 5xx error.
GET {{baseUrl}}{{hubspotPrefix}}/oauth2/callback?code=invalid_test_code&state=invalid_test_state


###
# 5. API Documentation Health Check
#
# Checks if the FastAPI documentation page is running.
# This is a good way to verify that the server is up.
GET {{baseUrl}}/docs

